require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FoodTypesController do

  # This should return the minimal set of attributes required to create a valid
  # FoodType. As you add validations to FoodType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all food_types as @food_types" do
      food_type = FoodType.create! valid_attributes
      get :index
      assigns(:food_types).should eq([food_type])
    end
  end

  describe "GET show" do
    it "assigns the requested food_type as @food_type" do
      food_type = FoodType.create! valid_attributes
      get :show, :id => food_type.id.to_s
      assigns(:food_type).should eq(food_type)
    end
  end

  describe "GET new" do
    it "assigns a new food_type as @food_type" do
      get :new
      assigns(:food_type).should be_a_new(FoodType)
    end
  end

  describe "GET edit" do
    it "assigns the requested food_type as @food_type" do
      food_type = FoodType.create! valid_attributes
      get :edit, :id => food_type.id.to_s
      assigns(:food_type).should eq(food_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FoodType" do
        expect {
          post :create, :food_type => valid_attributes
        }.to change(FoodType, :count).by(1)
      end

      it "assigns a newly created food_type as @food_type" do
        post :create, :food_type => valid_attributes
        assigns(:food_type).should be_a(FoodType)
        assigns(:food_type).should be_persisted
      end

      it "redirects to the created food_type" do
        post :create, :food_type => valid_attributes
        response.should redirect_to(FoodType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved food_type as @food_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoodType.any_instance.stub(:save).and_return(false)
        post :create, :food_type => {}
        assigns(:food_type).should be_a_new(FoodType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FoodType.any_instance.stub(:save).and_return(false)
        post :create, :food_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested food_type" do
        food_type = FoodType.create! valid_attributes
        # Assuming there are no other food_types in the database, this
        # specifies that the FoodType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FoodType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => food_type.id, :food_type => {'these' => 'params'}
      end

      it "assigns the requested food_type as @food_type" do
        food_type = FoodType.create! valid_attributes
        put :update, :id => food_type.id, :food_type => valid_attributes
        assigns(:food_type).should eq(food_type)
      end

      it "redirects to the food_type" do
        food_type = FoodType.create! valid_attributes
        put :update, :id => food_type.id, :food_type => valid_attributes
        response.should redirect_to(food_type)
      end
    end

    describe "with invalid params" do
      it "assigns the food_type as @food_type" do
        food_type = FoodType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoodType.any_instance.stub(:save).and_return(false)
        put :update, :id => food_type.id.to_s, :food_type => {}
        assigns(:food_type).should eq(food_type)
      end

      it "re-renders the 'edit' template" do
        food_type = FoodType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FoodType.any_instance.stub(:save).and_return(false)
        put :update, :id => food_type.id.to_s, :food_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested food_type" do
      food_type = FoodType.create! valid_attributes
      expect {
        delete :destroy, :id => food_type.id.to_s
      }.to change(FoodType, :count).by(-1)
    end

    it "redirects to the food_types list" do
      food_type = FoodType.create! valid_attributes
      delete :destroy, :id => food_type.id.to_s
      response.should redirect_to(food_types_url)
    end
  end

end
